bindings: cxx: fix build error
Due to a bad backport the build now fails with the following error:

line.cpp: In member function ‘gpiod::line_event gpiod::line::event_read() const’:
line.cpp:172:34: error: ‘struct gpiod::line_event’ has no member named ‘ts’
     ::std::chrono::seconds(event.ts.tv_sec)) +
                                  ^~
line.cpp:173:38: error: ‘struct gpiod::line_event’ has no member named ‘ts’
     ::std::chrono::nanoseconds(event.ts.tv_nsec);
                                      ^~
make[4]: *** [Makefile:557: libgpiodcxx_la-line.lo] Error 1

This change fixes it.

Fixes: 452e4bac0c85 ("bindings: cxx: fix event timestamp calculation for 32bit")
Signed-off-by: Bartosz Golaszewski <bgolaszewski@baylibre.com>